### ISSUE TITLE
Less MSIérables Symbol (Icon)

### ISSUE THREAD

**Issue by DARO75** [activescott/lessmsi#29]
Less MSIérables is a very good tool, but why has Less MSIérables no symbol (Icon) ? 
Could please create a Symbol?

it would be very good! a resolution of 256x256 would be perfect!

**Comment by arcanosam** [comment]
I always liked the icon located on top-left corner of the window.

Actually, I've always thought that was the real icon.

And since I know this tool, I've always get this icon by print-screen and I edit on gimp, export to png and set my shortcut with it.

I attached, if anyone want it.

![less_msireable_tool](https://user-images.githubusercontent.com/1272609/71518972-26d53800-2894-11ea-9909-c24684c1aa46.png)
