### ISSUE TITLE
lessmsi does not work...

### ISSUE THREAD

**Issue by DARO75** [activescott/lessmsi#52]
does not work with Windows 10 Build 10240! old .NET Version! Can you please publish a fully supported version? Thx's

**Comment by activescott** [comment]
I've finally got my hands on a copy of windows 10 to test with and found that almost everything works. The only thing that isn't working is the [Windows Explorer Integration](https://github.com/activescott/lessmsi#windows-explorer-integration): When attempting to add the shortcut it prompts to install .NET v3.5: 
![screen shot 2015-10-31 at 10 10 27 pm](https://cloud.githubusercontent.com/assets/213716/10867393/e23c5fe4-801c-11e5-87cb-b9d3a44b8e02.png)

I did some searching and found that in order to support Windows7 - Windows 10, it looks like .NET 4 is installed on all machines back to windows 7 (although Win7 does have to run Windows Update several times): http://superuser.com/a/298027/89383 .

So I'll go ahead and update everything to .NET v4 and try to get some testing done on Win7, Win8, & Win10 to verify.
